server:
  port: 9094

spring:
  application:
    name: ORDER-SERVICE

  data:
    mongodb:
      uri: mongodb+srv://user:user123@cluster1.rkdtr2z.mongodb.net/restaurantdb
      database: restaurantdb
      repositories:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
